### ISSUE TITLE
Update for actix 4.1?

### ISSUE THREAD

**Issue by SeriousBug** [eburghar/actix-cachecontrol-middleware#1]
Hey! Do you have any plans to update this for actix web 4.1, and to put it on crates.io? I can send a PR to help with it if you'd like, or if you are no longer working on it I can fork and maintain it.

**Comment by eburghar** [comment]
Yes you can send a PR.

I did an update some times ago (but left things as is). You can find it on a 'actix-4' branch. I just wanted to convert a bigger project to actix-web 4 before putting it on repo (in my todo list since a long time).

I never really thought about publishing it on crate.io (impostor syndrome ? ;) but if you want, fell free to fork an publish.

Thanks for reaching me anyway.

**Comment by eburghar** [comment]
branch merged and version bumped
